In [1]:
import numpy as np

# Function to generate Vandermonde matrix
def vandermonde_vector(input_vector, N, increasing=False):
    """
    Generate a Vandermonde matrix based on the input vector.

    Parameters:
    input_vector (array_like): Input vector.
    N (int): Number of columns in the output matrix.
    increasing (bool, optional): Determines the order of the powers in each output column.
                                 If False (default), the i-th output column is the input vector
                                 raised element-wise to the power of N - i - 1. If True, the
                                 order is reversed.

    Returns:
    ndarray: Vandermonde matrix.

    """
    input_vector = np.array(input_vector)
    if increasing:
        return np.column_stack([input_vector**i for i in range(N)])
    else:
        return np.column_stack([input_vector**(N-i-1) for i in range(N)])


# Function to calculate moving average
def moving_average(input_sequence, k):
    """
    Calculate the moving average of a sequence over a window size k.

    Parameters:
    input_sequence (array_like): Input sequence of values.
    k (int): Window size.

    Returns:
    ndarray: Moving average sequence.

    """
    input_sequence = np.array(input_sequence)
    n = len(input_sequence)
    return np.convolve(input_sequence, np.ones(k), mode='valid') / k


# Test the functions
if __name__ == "__main__":
    # Test Vandermonde function
    input_vector = [1, 2, 3, 4]
    N = 5
    print("Vandermonde matrix:")
    print(vandermonde_vector(input_vector, N))

    # Test moving average function
    input_sequence = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
    k = 3
    print("\nMoving average sequence:")
    print(moving_average(input_sequence, k))


Vandermonde matrix:
[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]]

Moving average sequence:
[  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]
